### ISSUE TITLE
Not able to create classifier using "toolbox/train-classifier.py" 

### ISSUE THREAD

**Issue by ameen4827** [cyhex/streamcrab#18]
while running "toolbox/train-classifier.py" i am getting following exception:

Traceback (most recent call last):
  File "toolbox/train-classifier.py", line 13, in <module>
    from smm import models
  File "/usr/local/lib/python2.7/dist-packages/nltk-2.0.4-py2.7.egg/nltk/classify/maxent.py", line 315, in train
    gaussian_prior_sigma, **cutoffs)
  File "/usr/local/lib/python2.7/dist-packages/nltk-2.0.4-py2.7.egg/nltk/classify/maxent.py", line 1440, in train_maxent_classifier_with_scipy
    model.fit(algorithm=algorithm)
  File "/usr/lib/python2.7/dist-packages/scipy/maxentropy/maxentropy.py", line 1026, in fit
    return model.fit(self, self.K, algorithm)
  File "/usr/lib/python2.7/dist-packages/scipy/maxentropy/maxentropy.py", line 226, in fit
    callback=callback)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 636, in fmin_cg
    gfk = myfprime(x0)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/usr/lib/python2.7/dist-packages/scipy/maxentropy/maxentropy.py", line 420, in grad
    G = self.expectations() - self.K
ValueError: operands could not be broadcast together with shapes (800) (1636)

could you please help me to create classifier.

**Comment by cyhex** [comment]
I could not recreate it, try collecting more tweets and rerun train-classifier.py

**Comment by cyhex** [comment]
closed due to inactivity
