### ISSUE TITLE
Error on run of test client

### ISSUE THREAD

**Issue by dwmcqueen** [cyhex/streamcrab#2]
After starting debug and running test client (python moodClientServerTest.py  in the "test" directory), see this error on the client window:

Traceback (most recent call last):
  File "moodClientServerTest.py", line 11, in <module>
    print MCC.classify(test_data, 'search')
  File "../../tracker/lib/moodClassifierClient.py", line 57, in classify
    self._readResults()
  File "../../tracker/lib/moodClassifierClient.py", line 28, in _readResults
    dataLen = int(dataLen)
ValueError: invalid literal for int() with base 10: ''

With this on the daemon window:

Exception happened during processing of request from ('127.0.0.1', 44979)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 582, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 639, in **init**
    self.handle()
  File "moodClassifierd.py", line 61, in handle
    raise e
RuntimeError: dictionary changed size during iteration

**Comment by cyhex** [comment]
hmm... i never saw this before, i have updated the moodClientServerTest.py, try to run it with new files and let me know whats up...

**Comment by dwmcqueen** [comment]
Looks good.
