### ISSUE TITLE
mongoengine.connection.ConnectionError: Cannot connect to database default : False is not a read preference.

### ISSUE THREAD

**Issue by venkatwilliams** [cyhex/streamcrab#22]
/dev/streamcrab$ sudo python toolbox/collect-tweets.py happy 2000
Traceback (most recent call last):
  File "toolbox/collect-tweets.py", line 28, in <module>
    models.connect()
  File "/home/venkat/dev/streamcrab/smm/models.py", line 125, in connect
    mongoengine.connect(**conf)
  File "build/bdist.linux-x86_64/egg/mongoengine/connection.py", line 173, in connect
  File "build/bdist.linux-x86_64/egg/mongoengine/connection.py", line 135, in get_connection
mongoengine.connection.ConnectionError: Cannot connect to database default :
False is not a read preference.

**Comment by cyhex** [comment]
make sure you have correct mongo configuration and mongo server is running
