### ISSUE TITLE
SMM - is there a missing file?

### ISSUE THREAD

**Issue by sp00** [cyhex/streamcrab#8]
Hi

Firstly, I have to say this SMM is fantastic and I'm looking forward to being able to implement some of the classifiers you mention...

I have a questions though, and hope you can help

I've run all the tests - per your readme and everything is 'OK'

when I try and initiate the program on my local machine though I get the following error -

python tests/moodClientServerTest.py

Traceback (most recent call last):
  File "tests/moodClientServerTest.py", line 4, in <module>
    from tracker.lib.moodClassifierClient import MoodClassifierTCPClient
ImportError: No module named tracker.lib.moodClassifierClient

can you provide any insight please?

Thanks in advance

**Comment by boorad** [comment]
@sp00 did you get this figured out?  I'm seeing the same thing.  Is the `python moodClassifierd.py debug` supposed to return to the shell, or just stay running in that terminal, and you run the `python tests/moodClientServerTest.py` command in another?

Guess I'll go digging.

**Comment by boorad** [comment]
ok, so you should cd down another level into tracker/tests before running the test.  I'll see about a pull request to clean up some docs and patch some code.

**Comment by amali** [comment]
Any one tried twitterCollector.py? It has been running for long time, with no data, output file in empty.
I got the following message too: maximum recursion depth exceeded in **instancecheck**

Any idea?

**Comment by cyhex** [comment]
New Version in development... Should fix a lot of hard coded stuff bugs etc..,

**Comment by misskbar** [comment]
when i do:

 python -m unittest discover tests

# EE....EEEEE..............

## ERROR: test_classifiedStream (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_classifiedStream
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_classifiedStream.py", line 1, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_classifierWorker (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_classifierWorker
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_classifierWorker.py", line 3, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_socketSession (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_socketSession
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_socketSession.py", line 1, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_trainedClassifiers (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_trainedClassifiers
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_trainedClassifiers.py", line 1, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_twitterWorker (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_twitterWorker
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_twitterWorker.py", line 4, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_twitterWorkerPool (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_twitterWorkerPool
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_twitterWorkerPool.py", line 3, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_twitterWorkerSleep (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_twitterWorkerSleep
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_twitterWorkerSleep.py", line 4, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

---

Ran 25 tests in 0.003s

FAILED (errors=7)
Karens-MacBook-Pro:streamcrab-master karenbar$ clear

Karens-MacBook-Pro:streamcrab-master karenbar$ python -m unittest discover tests

# EE....EEEEE..............

## ERROR: test_classifiedStream (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_classifiedStream
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_classifiedStream.py", line 1, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_classifierWorker (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_classifierWorker
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_classifierWorker.py", line 3, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_socketSession (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_socketSession
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_socketSession.py", line 1, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_trainedClassifiers (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_trainedClassifiers
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_trainedClassifiers.py", line 1, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_twitterWorker (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_twitterWorker
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_twitterWorker.py", line 4, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_twitterWorkerPool (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_twitterWorkerPool
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_twitterWorkerPool.py", line 3, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

# 

## ERROR: test_twitterWorkerSleep (unittest.loader.ModuleImportFailure)

ImportError: Failed to import test module: test_twitterWorkerSleep
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/karenbar/Downloads/streamcrab-master/tests/test_twitterWorkerSleep.py", line 4, in <module>
    from abstract import TestCaseDB
  File "/Users/karenbar/Downloads/streamcrab-master/tests/abstract.py", line 3, in <module>
    from smm.config import test_mongo_db
  File "smm/config.py", line 5, in <module>
    from smm.classifier.textprocessing import StopStemmTwitterProcessor, StopTwitterProcessor
ImportError: cannot import name StopStemmTwitterProcessor

---

Ran 25 tests in 0.002s

FAILED (errors=7)
